# Generated by Django 4.1.4 on 2022-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('science', '科学のこと'), ('food', '食のこと'), ('music', '音楽のこと')], max_length=10, verbose_name='カテゴリ'),
        ),
    ]
